stages:
  - build
  - deploy


# Build the React/JavaScript front-end
build-front-end-job:
  stage: build
  image: node:lts-bullseye

  variables:
    PUBLIC_URL: https://kristenjin811.gitlab.io/snowseekers/
    REACT_APP_UNSPLASH_API_KEY: ${REACT_APP_UNSPLASH_API_KEY}

  script:
    - cd ghi
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/build/


# Deploy the React/JavaScript front-end to GitLab pages
pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv ghi/build/ public
  artifacts:
    paths:
      - public
